### ISSUE TITLE
请问您在windows下启动要多长时间

### ISSUE THREAD

**Issue by lld2001** [xhcoding/.emacs.d#1]
我现在win7下用doom emacs，240个包，daemon启动要2分钟，正常启动30多秒。看见dashboard还会再卡20秒左右才能用。主要的包是orgmode,org-roam,magit,python。快受不了这速度了。想了解一下您的配置速度。

**Comment by xhcoding** [comment]
我这份配置没有做任何的优化，启动也很慢。
之前我也很关心启动速度，想尽办法优化，现在不纠结了，每天也只启动一两次，慢点就慢点。

**Comment by lld2001** [comment]
好的，谢谢。看来windos下就这样了

**Comment by lld2001** [comment]
好的，谢谢。看来windos下就这样了
